import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import CustomCursor from "@/components/CustomCursor"; // Import the cursor component

import "./globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Junaid Paramberi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className="antialiased">
        <CustomCursor />
        <Navbar />
        {children}
        <div className="gradient-bg">{/* Your content here */}</div>
        <Footer />
      </body>
    </html>
  );
}
